version: "3"
services:
  app:
    build: ./build/php-fpm
    restart: always
    user: web
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      WP_ENV: "${WP_ENV}"
      WP_HOME: "${WP_HOME}"
      WP_SITEURL: "${WP_SITEURL}"
    volumes:
      - ./bedrock/web:/bedrock/web
      - ./bedrock/config:/bedrock/config
      - ./bedrock/.env:/bedrock/.env
      - ./bedrock/composer.json:/bedrock/composer.json
      - ./bedrock/composer.lock:/bedrock/composer.lock
      - ./bedrock/phpcs.xml:/bedrock/phpcs.xml
      - ./bedrock/wp-cli.yml:/bedrock/wp-cli.yml

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3030
    volumes:
      - ./db:/var/lib/mysql

  redis:
    image: redis
    restart: always

  nginx:
    image: nginx
    restart: always
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bedrock/web:/bedrock/web
      - ./build/nginx/conf.d:/etc/nginx/conf.d
