version: '3'
services:
  bedrock:
    build: ./build/php-fpm
    restart: always
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
    environment:
      - DB_NAME="${db_name}"
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
      - DB_HOST=${db_host}
      - WP_ENV=${wp_env}
      - WP_HOME="${wp_home}"
      - WP_SITEURL="${wp_siteurl}"
    volumes:
      - ./bedrock:/bedrock

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_ROOT_USERNAME: ${db_user}
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_USERNAME: ${db_user}
      MYSQL_PASSWORD: ${db_password}
    volumes:
      - ./db:/var/lib/mysql

  redis:
    image: redis
    restart: always

  nginx:
    image: nginx
    restart: always
    depends_on:
      - bedrock
    links:
      - bedrock
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bedrock:/bedrock
      - ./build/nginx/conf.d:/etc/nginx/conf.d
