version: '3'
services:
  app:
    build: ./docker/php-fpm
    restart: always
    user: web
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: '${DB_HOST}'
      WP_ENV: '${WP_ENV}'
      WP_HOME: '${WP_HOME}'
      WP_SITEURL: '${WP_SITEURL}'
    volumes:
      - ./web:/bedrock/web
      - ./config:/bedrock/config
      - ./.env:/bedrock/.env
      - ./composer.json:/bedrock/composer.json
      - ./composer.lock:/bedrock/composer.lock
      - ./phpcs.xml:/bedrock/phpcs.xml
      - ./wp-cli.yml:/bedrock/wp-cli.yml

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3030
    volumes:
      - ./docker/db:/var/lib/mysql

  redis:
    image: redis
    restart: always

  nginx:
    image: nginx
    restart: always
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/bedrock/web
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
